# vim:ft=ansible:
---

- hosts: all
  sudo: yes
  tasks:
    - name: Install Apache
      yum:
        name={{item}}
        state=present
      with_items:
        - httpd
        - httpd-devel
    - name: Copy configuration files.
      copy:
        src:   "{{item.src}}"
        dest:  "{{item.dest}}"
        owner: root
        group: root
        mode:  644
      with_items:
        - {
        src: "./files/httpd.conf",
        dest: "/etc/httpd/conf/httpd.conf"
          }
        - {
        src: "./files/httpd-vhosts.conf",
        dest: "/etc/httpd/conf.d/vhosts.conf"
          }
    - name: Make sure Apache is started and configure it to run at boot
      service:
        name=httpd
        state=started
        enabled=yes


